//! Splits `tests/snapshot_scenes.slint` page-level `Snap*Page` Windows
//! out into per-category `crates/pages-<cat>/ui/_snapshot_scenes.slint`
//! files. Widget-level snap scenes stay in the root file.
//!
//! Was a one-off when the workspace was first split; kept here so the
//! same operation is reproducible if root snapshot_scenes.slint ever
//! grows page Snap wrappers again (e.g. someone copies a scene block
//! from history).

use crate::workspace_root;
use std::collections::BTreeMap;
use std::fs;

pub fn run() -> Result<(), Box<dyn std::error::Error>> {
    let root = workspace_root();
    let src_path = root.join("tests").join("snapshot_scenes.slint");
    let text = fs::read_to_string(&src_path)?;

    // 1. Pull `import { Cls } from "@mobile-pages-<cat>/<stem>.slint";` lines
    //    out of the source. These give us `Cls -> (cat, stem)`.
    let cls_to_meta = parse_pages_imports(&text);
    if cls_to_meta.is_empty() {
        println!(
            "{} has no @mobile-pages-* imports — nothing to split.",
            src_path.display()
        );
        return Ok(());
    }

    // 2. Walk every `export component Snap<X> inherits Window { … }` block.
    //    For each, find the inner `<PageCls> { … }` instance to decide
    //    whether this is a page snap (move it) or a widget snap (leave it).
    let blocks = collect_snap_blocks(&text, &cls_to_meta);

    // 3. Group by category and emit per-crate `_snapshot_scenes.slint`.
    let mut by_cat: BTreeMap<&str, Vec<&Block>> = BTreeMap::new();
    for b in &blocks {
        let (cat, _) = &cls_to_meta[&b.page_cls];
        by_cat.entry(cat.as_str()).or_default().push(b);
    }
    for (cat, entries) in &by_cat {
        let out_path = root
            .join("crates")
            .join(format!("pages-{cat}"))
            .join("ui")
            .join("_snapshot_scenes.slint");
        let mut buf = String::new();
        buf.push_str("// Auto-generated by `cargo xtask split-snapshots`.\n");
        buf.push_str("// Snap*Page wrappers for every page in this category. Compiled by\n");
        buf.push_str("// build.rs into a Rust module the root test runner re-exports.\n\n");
        buf.push_str("import { Theme } from \"@mobile-theme/theme.slint\";\n");
        for b in entries {
            let stem = &cls_to_meta[&b.page_cls].1;
            buf.push_str(&format!(
                "import {{ {cls} }} from \"{stem}.slint\";\n",
                cls = b.page_cls,
            ));
        }
        buf.push('\n');
        for b in entries {
            if !b.comment_block.is_empty() {
                buf.push_str(&b.comment_block);
                if !b.comment_block.ends_with('\n') {
                    buf.push('\n');
                }
            }
            buf.push_str(&format!(
                "export component {snap} inherits Window {{\n    preferred-width: 412px;\n    preferred-height: 892px;\n    background: Theme.background;\n    {cls} {{\n        width: parent.width;\n        height: parent.height;\n    }}\n}}\n\n",
                snap = b.snap_name,
                cls = b.page_cls,
            ));
        }
        fs::write(&out_path, format!("{}\n", buf.trim_end()))?;
        println!("wrote {} ({} scenes)", out_path.display(), entries.len());
    }

    // 4. Splice the page blocks + page imports out of the root file.
    let mut spans: Vec<(usize, usize)> = blocks.iter().map(|b| (b.start, b.end)).collect();
    spans.sort_by_key(|s| s.0);
    let mut trimmed = String::with_capacity(text.len());
    let mut cursor = 0;
    for (start, end) in spans {
        trimmed.push_str(&text[cursor..start]);
        cursor = end;
    }
    trimmed.push_str(&text[cursor..]);
    let trimmed = strip_pages_imports(&trimmed);
    let trimmed = collapse_blank_lines(&trimmed);

    fs::write(&src_path, &trimmed)?;
    println!(
        "trimmed {}: {} -> {} bytes ({} page Snap blocks moved)",
        src_path.display(),
        text.len(),
        trimmed.len(),
        blocks.len()
    );
    Ok(())
}

#[derive(Debug)]
struct Block {
    /// Inclusive byte offset of the first character to remove (the
    /// `export` line, or an immediately-preceding `// …` comment line).
    start: usize,
    /// Exclusive byte offset just past the closing `}` newline.
    end: usize,
    snap_name: String,
    page_cls: String,
    /// The contiguous `// …` block immediately above the `export`, if any,
    /// preserved verbatim for re-emission in the per-category file.
    comment_block: String,
}

/// Parse `import { Cls } from "@mobile-pages-<cat>/<stem>.slint";` lines.
fn parse_pages_imports(text: &str) -> BTreeMap<String, (String, String)> {
    let mut out = BTreeMap::new();
    for line in text.lines() {
        let line = line.trim_start();
        let Some(rest) = line.strip_prefix("import") else {
            continue;
        };
        let rest = rest.trim_start();
        let Some(rest) = rest.strip_prefix('{') else {
            continue;
        };
        let Some(close) = rest.find('}') else {
            continue;
        };
        let cls = rest[..close].trim().to_string();
        let after = rest[close + 1..].trim_start();
        let Some(after) = after.strip_prefix("from") else {
            continue;
        };
        let after = after.trim_start();
        let Some(after) = after.strip_prefix('"') else {
            continue;
        };
        let Some(quote_end) = after.find('"') else {
            continue;
        };
        let path = &after[..quote_end];
        let Some(rest) = path.strip_prefix("@mobile-pages-") else {
            continue;
        };
        let Some(slash) = rest.find('/') else {
            continue;
        };
        let cat = rest[..slash].to_string();
        let Some(stem) = rest[slash + 1..].strip_suffix(".slint") else {
            continue;
        };
        out.insert(cls, (cat, stem.to_string()));
    }
    out
}

fn collect_snap_blocks(text: &str, cls_to_meta: &BTreeMap<String, (String, String)>) -> Vec<Block> {
    let mut blocks = Vec::new();
    let prefix = "export component ";
    let mut idx = 0usize;
    while let Some(rel) = text[idx..].find(prefix) {
        let head_start = idx + rel;
        // The `export component` must be at column 0.
        if head_start != 0 && !text[..head_start].ends_with('\n') {
            idx = head_start + prefix.len();
            continue;
        }
        let after_prefix = head_start + prefix.len();
        let Some(line_end) = text[after_prefix..].find('\n').map(|i| after_prefix + i) else {
            break;
        };
        let header = &text[after_prefix..line_end];
        let mut header_tokens = header.split_whitespace();
        let name = header_tokens.next().unwrap_or("");
        let inherits_ok = header_tokens.next() == Some("inherits");
        let next_token = header_tokens.next();
        let is_window = matches!(next_token, Some(t) if t.starts_with("Window"));
        let is_snap = name.starts_with("Snap");
        if !(is_snap && inherits_ok && is_window) {
            idx = line_end + 1;
            continue;
        }
        // Find opening `{` (must be on the header line) and walk to the
        // matching `}`.
        let Some(open) = text[after_prefix..line_end]
            .find('{')
            .map(|o| after_prefix + o)
        else {
            idx = line_end + 1;
            continue;
        };
        let bytes = text.as_bytes();
        let mut depth: i32 = 1;
        let mut walker = open + 1;
        while walker < bytes.len() && depth > 0 {
            match bytes[walker] {
                b'{' => depth += 1,
                b'}' => depth -= 1,
                _ => {}
            }
            walker += 1;
        }
        if depth != 0 {
            // Unbalanced; bail out of further scanning.
            break;
        }
        let mut block_end = walker;
        if block_end < bytes.len() && bytes[block_end] == b'\n' {
            block_end += 1;
        }
        let body = &text[open + 1..walker - 1];

        // Locate the inner `<PageCls> { … }` instantiation — first line that
        // matches `    <UpperCamel> {` at exactly 4-space indent.
        let page_cls = body
            .lines()
            .find_map(|line| {
                let inner = line.strip_prefix("    ")?;
                if inner.starts_with(' ') {
                    return None;
                }
                let name = inner.split_whitespace().next()?;
                let first = name.chars().next()?;
                if !first.is_ascii_uppercase() {
                    return None;
                }
                if !inner.contains('{') {
                    return None;
                }
                Some(name.trim_end_matches('{').to_string())
            })
            .unwrap_or_default();

        if !cls_to_meta.contains_key(&page_cls) {
            idx = block_end;
            continue;
        }

        // Walk back over preceding `// …` comment lines.
        let mut block_start = head_start;
        let mut comment_block = String::new();
        loop {
            let before = &text[..block_start];
            let Some(nl) = before.rfind('\n') else { break };
            // `nl` is the newline ending the previous line; the previous
            // line itself is text[prev_line_start..nl].
            let prev_line_start = before[..nl].rfind('\n').map_or(0, |i| i + 1);
            let prev_line = &text[prev_line_start..nl];
            if prev_line.trim_start().starts_with("//") {
                comment_block.insert_str(0, &text[prev_line_start..nl + 1]);
                block_start = prev_line_start;
            } else {
                break;
            }
        }

        blocks.push(Block {
            start: block_start,
            end: block_end,
            snap_name: name.to_string(),
            page_cls,
            comment_block,
        });
        idx = block_end;
    }
    blocks
}

fn strip_pages_imports(text: &str) -> String {
    text.lines()
        .filter(|line| {
            let t = line.trim_start();
            if !t.starts_with("import") {
                return true;
            }
            !t.contains("\"@mobile-pages-")
        })
        .collect::<Vec<_>>()
        .join("\n")
}

fn collapse_blank_lines(text: &str) -> String {
    let mut out = String::with_capacity(text.len());
    let mut blank_run = 0;
    for line in text.split('\n') {
        if line.is_empty() {
            blank_run += 1;
            if blank_run <= 2 {
                out.push('\n');
            }
        } else {
            blank_run = 0;
            if !out.is_empty() {
                // We pushed a `\n` for the previous line's terminator.
            }
            out.push_str(line);
            out.push('\n');
        }
    }
    // Drop trailing newline introduced by the final push if the original
    // didn't end with one. (`split('\n')` yields an empty trailing entry
    // for a string ending in newline; the loop handled it.)
    out
}
